1:
  objective: binary
  metric: binary_logloss
  learning_rate: 0.1
  max_depth: 5
  n_estimators: 1000
  num_iterations: 100
  subsample: 0.8
  colsample_bytree: 0.8
  max_bin: 100
  num_leaves: 15
  min_data_in_leaf: 10

14:
  objective: binary
  metric: binary_logloss
  learning_rate: 0.01
  max_depth: 5
  n_estimators: 500
  num_iterations: 100
  subsample: 0.8
  colsample_bytree: 0.8
  max_bin: 100
  num_leaves: 15
  min_data_in_leaf: 10

15:
  objective: binary
  metric: binary_logloss
  learning_rate: 0.01
  max_depth: 4
  n_estimators: 500
  num_iterations: 100
  subsample: 0.8
  colsample_bytree: 0.8
  max_bin: 100
  num_leaves: 15
  min_data_in_leaf: 10

16:
  objective: binary
  metric: binary_logloss
  learning_rate: 0.01
  max_depth: 3
  n_estimators: 500
  num_iterations: 100
  subsample: 0.8
  colsample_bytree: 0.8
  max_bin: 100
  num_leaves: 15
  min_data_in_leaf: 10

17:
  objective: binary
  metric: binary_logloss
  learning_rate: 0.01
  max_depth: 3
  n_estimators: 100
  num_iterations: 100
  subsample: 0.8
  colsample_bytree: 0.8
  max_bin: 100
  num_leaves: 15
  min_data_in_leaf: 10

18:
  objective: binary
  metric: binary_logloss
  learning_rate: 0.01
  max_depth: 3
  n_estimators: 100
  num_iterations: 50
  subsample: 0.8
  colsample_bytree: 0.8
  max_bin: 100
  num_leaves: 15
  min_data_in_leaf: 10

19:
  objective: binary
  metric: binary_logloss
  learning_rate: 0.01
  max_depth: 3
  n_estimators: 100
  num_iterations: 50
  subsample: 0.8
  colsample_bytree: 0.8
  max_bin: 50
  num_leaves: 15
  min_data_in_leaf: 10

20:
  objective: binary
  metric: binary_logloss
  learning_rate: 0.01
  max_depth: 3
  n_estimators: 100
  num_iterations: 50
  subsample: 0.8
  colsample_bytree: 0.8
  max_bin: 25
  num_leaves: 15
  min_data_in_leaf: 10

21:
  objective: binary
  metric: binary_logloss
  learning_rate: 0.01
  max_depth: 3
  n_estimators: 100
  num_iterations: 50
  subsample: 0.8
  colsample_bytree: 0.8
  max_bin: 25
  num_leaves: 15
  min_data_in_leaf: 5

22:
  objective: binary
  metric: binary_logloss
  learning_rate: 0.01
  max_depth: 3
  n_estimators: 100
  num_iterations: 50
  subsample: 0.8
  colsample_bytree: 0.8
  max_bin: 25
  num_leaves: 5
  min_data_in_leaf: 5

23:
  objective: binary
  metric: binary_logloss
  learning_rate: 0.01
  max_depth: 3
  n_estimators: 100
  num_iterations: 50
  subsample: 0.8
  colsample_bytree: 0.8
  max_bin: 25
  num_leaves: 5
  min_data_in_leaf: 5
  lambda_l1: 5

24:
  objective: binary
  metric: binary_logloss
  learning_rate: 0.01
  max_depth: 3
  n_estimators: 100
  num_iterations: 50
  subsample: 0.8
  colsample_bytree: 0.8
  max_bin: 25
  num_leaves: 5
  min_data_in_leaf: 5
  lambda_l1: 0


25:
  objective: binary
  metric: binary_logloss
  learning_rate: 0.01
  max_depth: 3
  n_estimators: 100
  num_iterations: 50
  subsample: 0.8
  colsample_bytree: 0.8
  max_bin: 25
  num_leaves: 5
  min_data_in_leaf: 5
  lambda_l2: 0


26:
  objective: binary
  metric: binary_logloss
  learning_rate: 0.01
  max_depth: 3
  n_estimators: 100
  num_iterations: 50
  subsample: 0.8
  colsample_bytree: 0.8
  max_bin: 25
  num_leaves: 5
  min_data_in_leaf: 5
  lambda_l2: 5